### PR TITLE
added advanced options to optionsGroup

### PR DESCRIPTION
**Pull request by dxtr026**

### CODE REVIEW

**Comment by azizhk** [comment]
Can you ask the design team to update the mocks as well?

Also have you seen this: https://deploy-preview-321--pebble-web.netlify.com/?path=/story/recipes-optiongroupcheckboxsections--grouping-and-select-all
A "Select All" Group can accomplish what you are looking for.

**Comment by dxtr026** [comment]
@azizhk @ChaitanyaGadodia

**Comment by azizhk** [comment]
Let's get tests fixed.

**Comment by dxtr026** [comment]
Tests are not breaking, the build was unsuccessful as it was on my fork.

**Pull request merged**
